FROM            ubuntu:18.04

MAINTAINER      Lars Erdmann <lars.erdmann@uni-greifswald.de>

RUN             apt-get update --no-install-recommends && \
                apt-get install gnupg -y && \

                apt-get autoclean
